name: PROD Build & Deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.png"
      - ".vscode/**"
      - ".devcontainer/**"
      - "assets/**"
      - ".github/dependabot.yml"
      - "example.local.settings.json"

env:
  NODE_VERSION: 18.x # set this to the node version to use (supports 10.x, 12.x, 14.x)
  DISPLAY_NAME: Slack Draw Straws
  FUNCTION_APP_NAME: ms388-slack-draw-straws
  FUNCTION_APP_SLOT_NAME: production
  FUNCTION_APP_PATH: ./

jobs:
  build-and-deploy-prod:
    runs-on: windows-latest
    steps:
      - name: 📤 Notify Teams
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL_DEV }}
          deploy-card: true
          title: ${{ env.DISPLAY_NAME }} Deployment Started
          color: info

      - name: 👷 Checkout repo
        uses: actions/checkout@v4

      - name: 🏗️ Setup Node.js ${{ env.NODE_VERSION }} environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ⬆️ Update npm and install dependencies
        shell: bash
        run: npm i -g npm && npm ci --omit=dev

      - name: 🛫 Deploy function app to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          slot-name: ${{ env.FUNCTION_APP_SLOT_NAME }}
          package: ${{ env.FUNCTION_APP_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          respect-funcignore: true

      - name: ⚠️ Cancelled Notification
        if: ${{ cancelled() }}
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL_DEV }}
          deploy-card: true
          title: ${{ env.DISPLAY_NAME }} Deployment Cancelled
          color: warning

      - name: ⛔ Failure Notification
        if: ${{ failure() }}
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL_DEV }}
          deploy-card: true
          title: ${{ env.DISPLAY_NAME }} Deployment Failed
          color: failure

      - name: 🎉 Success Notification
        if: ${{ success() }}
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL_DEV }}
          deploy-card: true
          title: ${{ env.DISPLAY_NAME }} Deployment Successful
          color: success
